-- Outbox table for the outbox pattern
-- Version: 1.0
-- Safe for concurrent execution
-- Oracle compatible

-- Create schema version tracking table if not exists
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE schema_version (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version VARCHAR2(50) NOT NULL,
        applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        description VARCHAR2(1000)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- Table already exists
        ELSE RAISE;
        END IF;
END;
/

-- Create lock table for preventing concurrent initialization
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE schema_initialization_lock (
        instance_id VARCHAR2(255) PRIMARY KEY,
        acquired_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- Table already exists
        ELSE RAISE;
        END IF;
END;
/

-- Create outbox table
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE outbox_message (
        id RAW(16) PRIMARY KEY,
        payload CLOB NOT NULL,
        type VARCHAR2(255) NOT NULL,
        recipient VARCHAR2(255) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        processed_at TIMESTAMP NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- Table already exists
        ELSE RAISE;
        END IF;
END;
/

-- Create indexes
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_outbox_unprocessed_recipient_type
        ON outbox_message (recipient, type)
        WHERE processed_at IS NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- Index already exists
        ELSE RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_outbox_processed_at
        ON outbox_message (processed_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- Index already exists
        ELSE RAISE;
        END IF;
END;
/

-- Record schema version (Oracle uses WHERE NOT EXISTS for conflict handling)
INSERT INTO schema_version (version, description) 
SELECT '1.0', 'Initial outbox_message table and indexes'
FROM dual
WHERE NOT EXISTS (
    SELECT 1 FROM schema_version WHERE version = '1.0'
); 